name: Connect_build_test

on:
  push:
    branches-ignore:    
      - main
    paths:
      - 'Frends.MQTT.Connect/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.MQTT.Connect
      env_var_name_1: MQTT_publicBrokerAddress
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.MQTT_publicBrokerAddress }}
