name: Connect_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.MQTT.Connect/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.MQTT.Connect
      env_var_name_1: MQTT_publicBrokerAddress
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.MQTT_publicBrokerAddress }}
      