name: Receive_build_main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.MQTT.Receive/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.MQTT.Receive
      prebuild_command: |

        mkdir -p mosquitto/config

        openssl genrsa -out mosquitto/config/ca.key 2048
        openssl req -new -x509 -days 365 -key mosquitto/config/ca.key -out mosquitto/config/ca.crt -subj "/CN=MQTT-Test-CA"

        openssl genrsa -out mosquitto/config/server.key 2048
        openssl req -new -key mosquitto/config/server.key -out mosquitto/config/server.csr -subj "/CN=localhost"
        openssl x509 -req -in mosquitto/config/server.csr -CA mosquitto/config/ca.crt -CAkey mosquitto/config/ca.key -CAcreateserial -out mosquitto/config/server.crt -days 365

        touch mosquitto/config/passwd
        docker run --rm -v "$(pwd)/mosquitto/config:/mosquitto/config" eclipse-mosquitto mosquitto_passwd -b /mosquitto/config/passwd testuser testpass

        # List for debugging (optional)
        ls -la mosquitto/config

        docker run -d --name mqtt-broker \
          -p 1883:1883 -p 8883:8883 \
          -v "$(pwd)/mosquitto/config:/mosquitto/config" \
          eclipse-mosquitto
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
