name: Receive_build_main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.MQTT.Receive/**'
  workflow_dispatch:

jobs:
  build:
    services:
      mosquitto:
        image: eclipse-mosquitto:latest
        ports:
          - 1883:1883
        options: --health-cmd="mosquitto -v" --health-timeout=5m --health-retries=3
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.MQTT.Receive
      env_var_name_1: MQTT_publicBrokerAddress
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.MQTT_publicBrokerAddress }}
