name: Receive_release

on:
  workflow_dispatch:

jobs:
  build:
    services:
      mosquitto:
        image: eclipse-mosquitto:latest
        ports:
          - 1883:1883
        options: --health-cmd="mosquitto -v" --health-timeout=5m --health-retries=3
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@main
    with:
      workdir: Frends.MQTT.Receive
      env_var_name_1: MQTT_publicBrokerAddress
    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.MQTT_publicBrokerAddress }}
      