name: Receive_release

on:
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@main
    with:
      dotnet_version: 8.0.x
      workdir: Frends.MQTT.Receive
    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}
