name: Send_build_main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.MQTT.Send/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.MQTT.Send
      dotnet_version: 8.0.x
      prebuild_command: |
    
        echo "Starting MQTT services..."
        docker-compose -f Frends.MQTT.Send.Tests/docker-compose.yml up -d

        echo "Waiting for MQTT broker to pass healthcheck..."
        sleep 5
        docker exec mqtt-broker mosquitto_sub -h localhost -p 1883 -t '$SYS/broker/version' -C 1 -W 5 || true
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
