name: Send_build_test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.MQTT.Send/**'
  workflow_dispatch:

jobs:
  build:
    services:
      mosquitto:
        image: eclipse-mosquitto:latest
        ports:
          - 1883:1883
        options: --health-cmd="mosquitto -v" --health-timeout=5m --health-retries=3
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.MQTT.Send
      env_var_name_1: MQTT_publicBrokerAddress
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.MQTT_publicBrokerAddress }}
